name: "Set Up Internet Golf Deployment Client"
description: "Sets up the Internet Golf deployment client."
runs:
  using: node24
  main: dist/index.js
inputs:
  version:
    required: false
    # TODO: update automatically?
    default: "v0.2.1"
